language: node_js

branches:
  only:
  - master

node_js:
  - 10
  - 12

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: npm t && codecov
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
    - stage: github pages
      script: npm run docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: docs
        on:
          branch: master